CREATE TABLE Users(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Username VARCHAR2(105) not null,
    Password VARCHAR2(25) not null,
    First_Name VARCHAR2(105) not null,
    Last_Name VARCHAR2(105) not null,
    Result VARCHAR2(105) not null
);

CREATE TABLE Employeer(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Name VARCHAR2(105) not null,
    Username VARCHAR2(105) not null,
    Password VARCHAR2(25) not null
);

CREATE TABLE Campaign(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Title VARCHAR2(105) not null,
    Description VARCHAR2(105) not null,
    Employeer_Id NUMBER,
    CONSTRAINT fk_employeer_campaign FOREIGN KEY(Employeer_Id) REFERENCES Employeer(Id)
);


CREATE TABLE Employee_Campaign(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Employee_Status VARCHAR2(105) not null,
    Employee_Id NUMBER not null,
    Campaign_Id NUMBER not null,
    CONSTRAINT FK_user FOREIGN KEY(Employee_Id) REFERENCES Users(Id),
    CONSTRAINT FK_campaign FOREIGN KEY(Campaign_Id) REFERENCES Campaign(Id)
);

CREATE TABLE Selection(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Campaing_Id NUMBER NOT NULL,
    Employee_Id NUMBER NOT NULL,
    CONSTRAINT FK_user_seleciton FOREIGN KEY(Employee_Id) REFERENCES Users(Id),
    CONSTRAINT FK_campaign_selection FOREIGN KEY(Campaing_Id) REFERENCES Campaign(Id)
);

CREATE TABLE Interview(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Campaign_Id NUMBER NOT NULL,
    Employee_Id NUMBER NOT NULL,
    CONSTRAINT FK_user_interview FOREIGN KEY(Employee_Id) REFERENCES Users(Id),
    CONSTRAINT FK_campaign_interview FOREIGN KEY(Campaign_Id) REFERENCES Campaign(Id)
);

CREATE TABLE Super_HR(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Username VARCHAR2(105) not null,
    Password VARCHAR2(25) not null,
    Selection_Id  NUMBER NOT NULL,
    Interview_Id  NUMBER NOT NULL,
    CONSTRAINT FK_selection FOREIGN KEY(Selection_Id) REFERENCES Selection(Id),
    CONSTRAINT FK_interview FOREIGN KEY(Interview_Id) REFERENCES Interview(Id)
);

CREATE TABLE HR(
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 PRIMARY KEY,
    Username VARCHAR2(105) not null,
    Password VARCHAR2(25) not null,
    Selection_Id  NUMBER NOT NULL,
    Interview_Id  NUMBER NOT NULL,
    CONSTRAINT FK_selection_hr FOREIGN KEY(Selection_Id) REFERENCES Selection(Id),
    CONSTRAINT FK_interview_hr FOREIGN KEY(Interview_Id) REFERENCES Interview(Id)
);